/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import listeners.ListenerAddAttribute;
import edu.uci.ics.jung.graph.DirectedSparseGraph;
import graph.ComplexVertex;
import graph.MatchGraph;
import java.awt.GridLayout;
import java.awt.ItemSelectable;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import javafx.scene.input.KeyCode;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Thomas
 */
public class ViewAddAttribute extends javax.swing.JPanel {

    /**
     * Creates new form AddAttribute
     */
    
    
    ArrayList<JCheckBox> listOfCheckBox;
    
    /*public AddAttribute() {
        initComponents();
        listOfElement = new ArrayList<String>();
    }*/
    
    
    public ViewAddAttribute (String nom)
    {
        initComponents();
        jTextField1.setText(nom);
        listOfCheckBox = new ArrayList<>();
        jButton1.addActionListener(new ListenerAddAttribute(this));
    }
    
    public ViewAddAttribute ()
    {
        initComponents();
        
        listOfCheckBox = new ArrayList<>();
        jButton1.addActionListener(new ListenerAddAttribute(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Attribute name :");

        jTextField1.setEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel3.setText("Attribute list :");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Add Selected Vertex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            //TreePerso.addNode(jTextField1.getText());
            System.out.println("Validation du nom d'attribut");
    }//GEN-LAST:event_jTextField1KeyPressed
    
    
    public void addElementToJPanel(ArrayList<ComplexVertex> selectedVertex)
    {
        
      
        for ( ComplexVertex c : selectedVertex )
        {
            JCheckBox check = new JCheckBox(c.toString());
            check.setSelected(true);
            jPanel1.add(check);
            listOfCheckBox.add(check);

        }

        jPanel1.revalidate();
    }
    
    public void addElementToJPanel (HashSet<String> selectedVertex )
    {
        for ( String s : selectedVertex )
        {
            JCheckBox check = new JCheckBox(s);
            check.setSelected(true);
            jPanel1.add(check);
            listOfCheckBox.add(check);

        }

        jPanel1.revalidate();
    }
    
    public ArrayList<String> getElements ()
    {
        ArrayList<String> s = new ArrayList<>();
        for ( JCheckBox ch : listOfCheckBox )
        {
            s.add(ch.getText());
        }
        return s;
    }
    
    public void setElementToJPanel( ArrayList<String> selectedVertex )
    {
        jPanel1 = new JPanel();
        for ( String s : selectedVertex )
        {
            JCheckBox check = new JCheckBox(s);
            check.setSelected(true);
            jPanel1.add(check);
            listOfCheckBox.add(check);

        }

        jPanel1.revalidate();
    }
    
   
    
    public String getNameAttribute()
    {
        return jTextField1.getText();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
